#!/usr/bin/env python3
"""Reference implementation for the PageCurlSolver golden test fixture.

This script mirrors the cone deformation math in cpp/PageCurlSolver.cpp exactly
and emits both tests/golden.json (human readable) and tests/GoldenData.h
(machine readable, checked into the repo).
"""
import json
import math

PAGE_WIDTH = 200.0
PAGE_HEIGHT = 300.0
MESH_COLS = 3
MESH_ROWS = 3
PROGRESS = 0.75
APEX = -PAGE_HEIGHT * 1.5
K_MIN_THETA = 0.15
K_MAX_ROTATION = math.pi * 0.95


def clamp(v, lo, hi):
    return max(lo, min(v, hi))


def lerp(a, b, t):
    return a + (b - a) * t


def deform(u, v, theta, apex, rho):
    dx = u
    dy = v - apex
    R = math.hypot(dx, dy)
    if R < 1e-12:
        return u, v

    sin_theta = math.sin(theta)
    cos_theta = math.cos(theta)
    sin_rho = math.sin(rho)
    cos_rho = math.cos(rho)

    safe_sin_theta = max(sin_theta, 1e-12)
    r = R * sin_theta
    alpha = math.asin(clamp(dx / R, -1.0, 1.0))
    beta = alpha / safe_sin_theta

    x1 = r * math.sin(beta)
    y1 = R + apex - r * (1.0 - math.cos(beta)) * sin_theta
    z1 = r * (1.0 - math.cos(beta)) * cos_theta

    x2 = x1 * cos_rho - z1 * sin_rho
    y2 = y1
    return x2, y2


def build_grid():
    cols, rows = MESH_COLS, MESH_ROWS
    vertex_count = (cols + 1) * (rows + 1)

    theta = lerp(K_MIN_THETA, math.pi / 2.0, 1.0 - PROGRESS)
    rho = PROGRESS * K_MAX_ROTATION

    positions = []
    uvs = []
    indices = []

    for row in range(rows + 1):
        for col in range(cols + 1):
            u = PAGE_WIDTH * col / cols
            v = PAGE_HEIGHT * row / rows
            uvu = col / cols
            uvv = row / rows

            x, y = deform(u, v, theta, APEX, rho)
            positions.extend([x, y])
            uvs.extend([uvu, uvv])

    # Back vertices share positions, mirrored UVs.
    for row in range(rows + 1):
        for col in range(cols + 1):
            idx = row * (cols + 1) + col
            positions.extend([positions[idx * 2], positions[idx * 2 + 1]])
            uvs.extend([1.0 - col / cols, row / rows])

    vpr = cols + 1
    for row in range(rows):
        for col in range(cols):
            a = col + row * vpr
            b = col + 1 + row * vpr
            c = col + (row + 1) * vpr
            d = col + 1 + (row + 1) * vpr
            indices.extend([a, b, d, d, c, a])

    front_count = len(indices)

    for row in range(rows):
        for col in range(cols):
            a = col + row * vpr + vertex_count
            b = col + 1 + row * vpr + vertex_count
            c = col + (row + 1) * vpr + vertex_count
            d = col + 1 + (row + 1) * vpr + vertex_count
            indices.extend([a, d, b, d, a, c])

    back_start = front_count
    back_count = len(indices) - front_count

    return {
        "pageWidth": PAGE_WIDTH,
        "pageHeight": PAGE_HEIGHT,
        "meshCols": MESH_COLS,
        "meshRows": MESH_ROWS,
        "progress": PROGRESS,
        "theta": theta,
        "apex": APEX,
        "rho": rho,
        "positions": positions,
        "uvs": uvs,
        "indices": indices,
        "frontRange": {"start": 0, "count": front_count},
        "backRange": {"start": back_start, "count": back_count},
    }


def to_cpp_array(name, values, dtype="float"):
    body = ", ".join(str(v) for v in values)
    size = len(values)
    if dtype == "float":
        return f"  inline constexpr std::array<float, {size}> {name} = {{{body}}};"
    elif dtype == "uint16_t":
        vals = ", ".join(f"{int(v)}u" for v in values)
        return f"  inline constexpr std::array<uint16_t, {size}> {name} = {{{vals}}};"
    raise ValueError(dtype)


if __name__ == "__main__":
    data = build_grid()

    with open("tests/golden.json", "w") as f:
        json.dump(data, f, indent=2)

    header = f"""#pragma once
// Auto-generated by tests/generate_golden.py. Do not edit by hand.
#include <array>
#include <cstdint>

namespace tests::golden {{
  inline constexpr float PAGE_WIDTH = {data["pageWidth"]}f;
  inline constexpr float PAGE_HEIGHT = {data["pageHeight"]}f;
  inline constexpr int MESH_COLS = {data["meshCols"]};
  inline constexpr int MESH_ROWS = {data["meshRows"]};
  inline constexpr float PROGRESS = {data["progress"]}f;
  inline constexpr float THETA = {data["theta"]}f;
  inline constexpr float APEX = {data["apex"]}f;
  inline constexpr float RHO = {data["rho"]}f;
  inline constexpr size_t FRONT_START = {data["frontRange"]["start"]};
  inline constexpr size_t FRONT_COUNT = {data["frontRange"]["count"]};
  inline constexpr size_t BACK_START = {data["backRange"]["start"]};
  inline constexpr size_t BACK_COUNT = {data["backRange"]["count"]};

{to_cpp_array("POSITIONS", data["positions"])}
{to_cpp_array("UVS", data["uvs"])}
{to_cpp_array("INDICES", data["indices"], "uint16_t")}
}}
"""
    with open("tests/GoldenData.h", "w") as f:
        f.write(header)

    print("Wrote tests/golden.json and tests/GoldenData.h")
